REM clarifai

SET  FD_CLARIFAI_KEY=1234567890

REM database

SET FD_DB_TABLE_LOGIN=login
SET FD_DB_TABLE_USER=user

SET FD_DB_HOST=host
SET FD_DB_USER=user
SET FD_DB_PASSWORD=password
SET FD_DB_DATABASE=database